server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path: /
spring:
  application:
    name: test-thymeleaf
  thymeleaf:
    prefix: classpath:templates/views/
    cache: off
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/account?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.n25171.tk.mybatis.entity
  mapper-locations: classpath:mapper/*.xml


